---
title: "Running in parallel"
author: "Bob Verity"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This vignette demonstrates how to run *rmaverick* in parallel, making use of multiple cores if they are available.

```{r, echo=FALSE}
set.seed(1)
library(rmaverick)
```

Install and load the "parallel" package

```{r, eval = FALSE}
install.packages("parallel")
```

```{r}
library(parallel)
```

Simulate some data etc.

```{r}
set.seed(1)
mysim <- sim_data(n = 50, loci = 10, K = 3, admix_on = FALSE)

myproj <- mavproject()
myproj <- bind_data(myproj, mysim$data, ID_col = 1, pop_col = 2, ploidy_col = 3)
myproj <- new_set(myproj, admix_on = FALSE)
```

Detect cores

```{r}
cores <- detectCores()
```

Make a cluster

```{r, eval = FALSE}
cl <- makeCluster(cores)
```

Pass in the cluster

```{r, eval = FALSE}
myproj <- run_mcmc(myproj, K = 1:5, burnin = 1e3, samples = 1e3, rungs = 10, cluster = cl)
```

Terminate the cluster

```{r, eval = FALSE}
stopCluster(cl)
```



