// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// example_mcmc_cpp
Rcpp::List example_mcmc_cpp(Rcpp::NumericVector x, Rcpp::List args_params);
RcppExport SEXP _rmaverick_example_mcmc_cpp(SEXP xSEXP, SEXP args_paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type args_params(args_paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(example_mcmc_cpp(x, args_params));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rmaverick_example_mcmc_cpp", (DL_FUNC) &_rmaverick_example_mcmc_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_rmaverick(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
