# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generate_scaffolds_cpp <- function(args) {
    .Call('_rmaverick_generate_scaffolds_cpp', PACKAGE = 'rmaverick', args)
}

run_mcmc_cpp <- function(args) {
    .Call('_rmaverick_run_mcmc_cpp', PACKAGE = 'rmaverick', args)
}

GTI_evidence_sim_cpp <- function(args) {
    .Call('_rmaverick_GTI_evidence_sim_cpp', PACKAGE = 'rmaverick', args)
}

log_sum <- function(logA, logB) {
    .Call('_rmaverick_log_sum', PACKAGE = 'rmaverick', logA, logB)
}

call_hungarian_cpp <- function(args) {
    .Call('_rmaverick_call_hungarian_cpp', PACKAGE = 'rmaverick', args)
}

