# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_mcmc_cpp <- function(args) {
    .Call(`_rmaverick_run_mcmc_cpp`, args)
}

GTI_posterior_K_sim_cpp <- function(args) {
    .Call(`_rmaverick_GTI_posterior_K_sim_cpp`, args)
}

GTI_integrated_K_sim_cpp <- function(args) {
    .Call(`_rmaverick_GTI_integrated_K_sim_cpp`, args)
}

log_sum <- function(logA, logB) {
    .Call(`_rmaverick_log_sum`, logA, logB)
}

call_hungarian_cpp <- function(args) {
    .Call(`_rmaverick_call_hungarian_cpp`, args)
}

