# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

example_mcmc_cpp <- function(x, args_params) {
    .Call('_rmaverick_example_mcmc_cpp', PACKAGE = 'rmaverick', x, args_params)
}

